name: Hourly Traffic Update

on:
  schedule:
    - cron: '*/15 * * * *'  # Se ejecuta cada hora en punto
  workflow_dispatch:      # Permite ejecutarlo manualmente para probar

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: Rscript -e 'install.packages("httr2")'

      - name: Run download script
        run: Rscript scripts/download_traffic.R

      - name: Commit and Push
        run: |
          git config --global user.name "TrafficBot"
          git config --global user.email "actions@github.com"
          git add data/*.geojson
          git commit -m "Update traffic data: $(date)"
          git push
